export const pieceBlackIds = [
    "pawn_b1",
    "pawn_b2",
    "pawn_b3",
    "pawn_b4",
    "pawn_b5",
    "pawn_b6",
    "pawn_b7",
    "pawn_b8",
    "rook_b1",
    "rook_b2",
    "knight_b1",
    "knight_b2",
    "bishop_b1",
    "bishop_b2",
    "queen_b",
    "king_b",
];

export const pieceWhiteIds = [
    "pawn_w1",
    "pawn_w2",
    "pawn_w3",
    "pawn_w4",
    "pawn_w5",
    "pawn_w6",
    "pawn_w7",
    "pawn_w8",
    "rook_w1",
    "rook_w2",
    "knight_w1",
    "knight_w2",
    "bishop_w1",
    "bishop_w2",
    "queen_w",
    "king_w",
];